matrix:
- name: markdown
  aspell:
    lang: en
    d: en_US
    mode: markdown
    ignore-case: true
  dictionary:
    wordlists:
      - .github/workflows/config/spellcheck.wordlist.txt
    encoding: utf-8
  pipeline:
  - pyspelling.filters.context:
      context_visible_first: true
      delimiters:
      - open: ':'
        content: '[\w-]+'
        close: ':'
      # ignore attr_list {: .* :}
      - open: '{:'
        close: ':}'
  - pyspelling.filters.markdown:
      markdown_extensions:
      - pymdownx.superfences
      - pymdownx.snippets
      - attr_list
  - pyspelling.filters.html:
      comments: false
      attributes:
      - title
      - alt
      ignores:
      - 'code, pre, img'
  - pyspelling.filters.url:
  sources:
  - '**/*.md'
  default_encoding: utf-8
