name: check

# restricting branches prevents jobs from being run twice since
# a push to a pull request triggers two events.
on:
  workflow_dispatch:
  pull_request_target:
    branches:
      - "*"
  push:
    branches:
      - main


jobs:

  build:  # --------------------------------------------------------------------
    runs-on: ubuntu-20.04
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
          cache: 'pip'
      - run: echo "MKDOCS_MATERIAL_VERSION=$(cat .mkdocs-material.version)" >> $GITHUB_ENV
      - run: |
          pip install git+https://${GH_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git@${MKDOCS_MATERIAL_VERSION}
          pip install -r requirements.txt
          mkdocs gh-deploy --force


  yamllint: # ----------------------------------------------------------------
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - id: getfiles
        run: |
          echo "::set-output name=files::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep '.yml' | xargs)"
      - uses: ibiqlik/action-yamllint@v3
        if: ${{ steps.getfiles.outputs.files != '' }}
        with:
          file_or_dir: ${{ steps.getfiles.outputs.files }} 
          config_file: .yamllint


  mklint: # ----------------------------------------------------------------
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - id: getfiles
        run: |
          echo "::set-output name=files::$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} | grep '.md' | xargs)"
      - uses: nosborn/github-action-markdown-cli@v1.1.1
        if: ${{ steps.getfiles.outputs.files != '' }}
        with:
          files: ${{ steps.getfiles.outputs.files }} 
          config_file: .markdownlintrc


  linkcheck: # -------------------------------------------------------------
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2


